### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by sharynneazhar** [VeronikaFG/Attempt#1]
https://github.com/VeronikaFG/TheBooksApp/blob/41f8406a911f12b923f992de119406337d31f922/src/SearchBook.js#L36

Not all search results will have a thumbnail. Try searching for `biography` in the search page. Update your code to handle books without a thumbnail. Consider using a [placeholder](https://placeholder.com/) when a thumbnail image does not exist in the response. 

https://github.com/VeronikaFG/TheBooksApp/blob/41f8406a911f12b923f992de119406337d31f922/src/BookLibrary.js#L73

The errors you are receiving in the console are due to incorrect `PropTypes`. For example, here in `BookLibrary`, you set the PropType to expect an `array`. However, what is being returned from the API is an `object`. Notice in [App.js](https://github.com/VeronikaFG/TheBooksApp/blob/41f8406a911f12b923f992de119406337d31f922/src/App.js#L59-L61), you are passing the entire state *object* to `BookLibrary`. 

https://github.com/VeronikaFG/TheBooksApp/blob/41f8406a911f12b923f992de119406337d31f922/src/SearchBook.js#L74

Also a PropType error. Is `query` expected to be an `object` or a `string`?

https://github.com/VeronikaFG/TheBooksApp/blob/41f8406a911f12b923f992de119406337d31f922/src/SearchBook.js#L77

Also a PropType error. Is `userBooks` expected to be an `object` or an `array`?

Other than these, everything seems to be working correctly. 🙂

**Comment by VeronikaFG** [comment]
Thank you very much Sharynne! 🙂
